-- =============================================================
-- run_0011_0013_0014.sql
-- Combined catch-up bundle: paste the whole thing into the Supabase
-- SQL Editor and hit Run once.
--
-- Order matters. 0011 creates public.lab_parameters, which 0013's
-- patient_lab_results references with a foreign key -- running 0013
-- on its own is what produced:
--   ERROR: 42P01: relation "public.lab_parameters" does not exist
--
-- Each migration is its own transaction, and all three are safe to
-- re-run, so this bundle is safe even if part of it already applied.
-- =============================================================



-- ####################  0011_lab_parameters.sql  ####################

-- =============================================================
-- 0011_lab_parameters.sql
-- Reference catalog of lab test parameters (category/units/reference
-- range), mirroring SIMA's public.lab_parameters. Used as an
-- autocomplete/validation catalog when recording a result, not
-- patient data itself.
--
-- Note: SIMA's UI also reads a public.patient_lab_results table (results
-- joined to this catalog via parameter_id) that this app doesn't have
-- yet either -- this migration only adds the reference catalog, not
-- that results table. See docs/sima-interface.md.
--
-- Safe to re-run.
-- =============================================================

begin;

create table if not exists public.lab_parameters (
  id              bigint generated by default as identity primary key,
  category        text,
  test_name       text not null,
  units           text,
  reference_range text,
  created_at      timestamptz not null default now(),
  constraint lab_parameters_test_name_key unique (test_name)
);

alter table public.lab_parameters enable row level security;

drop policy if exists lab_parameters_select on public.lab_parameters;
create policy lab_parameters_select on public.lab_parameters
  for select to authenticated
  using (app.is_staff());

drop policy if exists lab_parameters_write on public.lab_parameters;
create policy lab_parameters_write on public.lab_parameters
  for all to authenticated
  using (app.has_role('owner', 'admin', 'doctor', 'nurse', 'lab_tech'))
  with check (app.has_role('owner', 'admin', 'doctor', 'nurse', 'lab_tech'));

grant select, insert, update on public.lab_parameters to authenticated;

insert into public.lab_parameters (category, test_name, units, reference_range) values
  ('KIDNEY',    'eGFR (CKD-EPI)',          'mL/min/1.73m2', '>= 90'),
  ('KIDNEY',    'Serum Creatinine',        'mg/dL',         '0.70 - 1.30'),
  ('KIDNEY',    'BUN (Blood Urea Nitrogen)', 'mg/dL',       '7 - 20'),
  ('LIPIDS',    'Total Cholesterol',       'mg/dL',         '< 200'),
  ('LIPIDS',    'LDL Cholesterol (Calc)',  'mg/dL',         '< 100'),
  ('LIPIDS',    'HDL Cholesterol',         'mg/dL',         '> 35'),
  ('LIPIDS',    'Triglycerides',           'mg/dL',         '< 150'),
  ('GLYCAEMIC', 'HbA1c',                   '%',             '4.0 - 5.6'),
  ('GLYCAEMIC', 'Fasting Blood Glucose',   'mg/dL',         '70 - 99'),
  ('HEMATOLOGY','RBC Count',               'M/ul',          '4.5 - 6.5'),
  ('HEMATOLOGY','Hemoglobin',              'g/dL',          '13 - 18'),
  ('HEMATOLOGY','Hematocrit',              '%',             '40 - 54'),
  ('HEMATOLOGY','MCV',                     'fl',            '80 - 94'),
  ('HEMATOLOGY','WBC Count',               'K/ul',          '4.0 - 11.0'),
  ('HEMATOLOGY','Platelet Count',          'K/ul',          '150 - 450'),
  ('LIVER',     'ALT (SGPT)',              'U/L',           '7 - 56'),
  ('LIVER',     'AST (SGOT)',              'U/L',           '10 - 40'),
  ('LIVER',     'ALP (Alkaline Phosphatase)', 'U/L',        '44 - 147'),
  ('ELECTROLYTES', 'Sodium',               'mmol/L',        '135 - 145'),
  ('ELECTROLYTES', 'Potassium',            'mmol/L',        '3.5 - 5.1'),
  ('THYROID',   'TSH',                     'uIU/mL',        '0.4 - 4.0')
on conflict (test_name) do nothing;

revoke all on all tables    in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke all on all functions in schema public from anon;

insert into app.schema_migrations (version, name)
values ('0011', 'lab_parameters')
on conflict (version) do nothing;

commit;


-- ####################  0013_outpatient_extras.sql  ####################

-- =============================================================
-- 0013_outpatient_extras.sql
-- Four outpatient-appropriate features carried over from SIMA's UI
-- that never had a backing table in this schema: the doctor's
-- current-medications reference list, internal staff notes +
-- routing, the patient contact log, lab results (against the
-- 0011 lab_parameters catalog), and a doctor's own list of
-- locations they see patients at.
--
-- Deliberately NOT included here: patient_orders (a full nurse
-- Care Queue / medication-administration-record system with
-- pharmacy stock deduction) and admissions (bed/ward/room
-- tracking) -- both are inpatient hospital workflows, and
-- admissions specifically is the bed-board feature this project
-- excluded from day one. Their leftover UI in PatientsDirectory
-- is removed in the same change as this migration, not built out.
--
-- Safe to re-run.
-- =============================================================

begin;

-- -------------------------------------------------------------
-- Current medications -- a doctor's own med-rec reference list of
-- what the patient is taking. Deliberately separate from any
-- nurse-facing standing order / administration schedule: just a
-- drug name + note the doctor can add, edit, or delete any time.
-- -------------------------------------------------------------
create table if not exists public.patient_medications (
  id          uuid primary key default gen_random_uuid(),
  patient_id  uuid not null references public.patients (id) on delete cascade,
  drug_name   text not null,
  note        text,
  created_by  uuid references public.staff (id) on delete set null,
  created_at  timestamptz not null default now()
);

create index if not exists patient_medications_patient_idx on public.patient_medications (patient_id, created_at desc);

-- -------------------------------------------------------------
-- Staff notes -- an internal memo attached to a patient, optionally
-- routed to a role and/or a specific staff member. Kept separate
-- from patient_contact_log (which is the short, broadly-readable
-- summary line) so clinical detail in the note body gets the
-- tighter read access below.
-- -------------------------------------------------------------
create table if not exists public.staff_notes (
  id          uuid primary key default gen_random_uuid(),
  patient_id  uuid not null references public.patients (id) on delete cascade,
  body        text not null,
  created_by  uuid references public.staff (id) on delete set null,
  created_at  timestamptz not null default now()
);

create index if not exists staff_notes_patient_idx on public.staff_notes (patient_id, created_at desc);

create table if not exists public.staff_note_recipients (
  id                 uuid primary key default gen_random_uuid(),
  staff_note_id      uuid not null references public.staff_notes (id) on delete cascade,
  recipient_role     public.staff_role,
  recipient_user_id  uuid references public.staff (id) on delete cascade,
  constraint staff_note_recipients_target_chk check (recipient_role is not null or recipient_user_id is not null)
);

create index if not exists staff_note_recipients_note_idx on public.staff_note_recipients (staff_note_id);
create index if not exists staff_note_recipients_user_idx on public.staff_note_recipients (recipient_user_id) where recipient_user_id is not null;

-- -------------------------------------------------------------
-- Contact log -- a short, broadly-readable record of patient
-- contact (phone calls, messages), optionally linking to a fuller
-- staff_notes entry for clinical detail.
-- -------------------------------------------------------------
create table if not exists public.patient_contact_log (
  id            uuid primary key default gen_random_uuid(),
  patient_id    uuid not null references public.patients (id) on delete cascade,
  entry_type    text not null check (entry_type in ('nurse_contact', 'provider_contact', 'secretary_contact', 'phone_call', 'message')),
  actor         text not null check (actor in ('patient', 'secretary', 'nurse', 'provider', 'admin', 'other')),
  summary       text not null,
  staff_note_id uuid references public.staff_notes (id) on delete set null,
  logged_by     uuid references public.staff (id) on delete set null,
  occurred_at   timestamptz not null default now()
);

create index if not exists patient_contact_log_patient_idx on public.patient_contact_log (patient_id, occurred_at desc);

-- -------------------------------------------------------------
-- Lab results -- individual parameter results against the
-- 0011_lab_parameters catalog. Populated either by hand or by the
-- document-analyzer extraction flow.
-- -------------------------------------------------------------
create table if not exists public.patient_lab_results (
  id           uuid primary key default gen_random_uuid(),
  patient_id   uuid not null references public.patients (id) on delete cascade,
  parameter_id bigint not null references public.lab_parameters (id) on delete restrict,
  result_value text not null,
  is_abnormal  boolean not null default false,
  created_by   uuid references public.staff (id) on delete set null,
  created_at   timestamptz not null default now()
);

create index if not exists patient_lab_results_patient_idx on public.patient_lab_results (patient_id, created_at desc);

-- -------------------------------------------------------------
-- Doctor locations -- a doctor's own list of places they see
-- patients (clinics, home visits), for tagging appointments/notes.
-- -------------------------------------------------------------
create table if not exists public.doctor_locations (
  id         uuid primary key default gen_random_uuid(),
  doctor_id  uuid not null references public.staff (id) on delete cascade,
  name       text not null,
  is_active  boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists doctor_locations_doctor_idx on public.doctor_locations (doctor_id, sort_order);

-- =============================================================
-- POLICIES
-- =============================================================

alter table public.patient_medications  enable row level security;
alter table public.staff_notes          enable row level security;
alter table public.staff_note_recipients enable row level security;
alter table public.patient_contact_log  enable row level security;
alter table public.patient_lab_results  enable row level security;
alter table public.doctor_locations     enable row level security;

drop policy if exists patient_medications_select on public.patient_medications;
create policy patient_medications_select on public.patient_medications
  for select to authenticated
  using (app.can_access_patient(patient_id));

drop policy if exists patient_medications_write on public.patient_medications;
create policy patient_medications_write on public.patient_medications
  for all to authenticated
  using (app.has_role('owner', 'admin', 'doctor', 'nurse') and app.can_access_patient(patient_id))
  with check (app.has_role('owner', 'admin', 'doctor', 'nurse') and app.can_access_patient(patient_id));

-- Staff notes: visible to the author, admins, anyone with a care
-- relationship to the patient, or an explicit routed recipient
-- (by role or by name) -- so routing a note to e.g. receptionist
-- works even for staff who don't otherwise have chart access.
drop policy if exists staff_notes_select on public.staff_notes;
create policy staff_notes_select on public.staff_notes
  for select to authenticated
  using (
    created_by = app.staff_id()
    or app.is_admin()
    or app.can_access_patient(patient_id)
    or exists (
      select 1 from public.staff_note_recipients r
      where r.staff_note_id = staff_notes.id
        and (r.recipient_user_id = app.staff_id() or (r.recipient_role is not null and app.has_role(r.recipient_role)))
    )
  );

drop policy if exists staff_notes_insert on public.staff_notes;
create policy staff_notes_insert on public.staff_notes
  for insert to authenticated
  with check (app.is_staff() and created_by = app.staff_id());

drop policy if exists staff_notes_update on public.staff_notes;
create policy staff_notes_update on public.staff_notes
  for update to authenticated
  using (app.is_admin() or created_by = app.staff_id())
  with check (app.is_admin() or created_by = app.staff_id());

drop policy if exists staff_notes_delete on public.staff_notes;
create policy staff_notes_delete on public.staff_notes
  for delete to authenticated
  using (app.is_admin());

-- Recipient rows are just routing metadata, not clinical content --
-- readable by any staff, but only insertable alongside a note the
-- staff member themselves authored.
drop policy if exists staff_note_recipients_select on public.staff_note_recipients;
create policy staff_note_recipients_select on public.staff_note_recipients
  for select to authenticated
  using (app.is_staff());

drop policy if exists staff_note_recipients_insert on public.staff_note_recipients;
create policy staff_note_recipients_insert on public.staff_note_recipients
  for insert to authenticated
  with check (exists (
    select 1 from public.staff_notes n
    where n.id = staff_note_id and n.created_by = app.staff_id()
  ));

drop policy if exists staff_note_recipients_delete on public.staff_note_recipients;
create policy staff_note_recipients_delete on public.staff_note_recipients
  for delete to authenticated
  using (app.is_admin());

-- Contact log: the summary line is meant to stay non-clinical (put
-- clinical detail in the attached staff_note instead), so it's
-- readable clinic-wide like a shared front-desk log.
drop policy if exists patient_contact_log_select on public.patient_contact_log;
create policy patient_contact_log_select on public.patient_contact_log
  for select to authenticated
  using (app.is_staff());

drop policy if exists patient_contact_log_insert on public.patient_contact_log;
create policy patient_contact_log_insert on public.patient_contact_log
  for insert to authenticated
  with check (app.is_staff() and logged_by = app.staff_id());

drop policy if exists patient_contact_log_update on public.patient_contact_log;
create policy patient_contact_log_update on public.patient_contact_log
  for update to authenticated
  using (app.is_admin() or logged_by = app.staff_id())
  with check (app.is_admin() or logged_by = app.staff_id());

drop policy if exists patient_contact_log_delete on public.patient_contact_log;
create policy patient_contact_log_delete on public.patient_contact_log
  for delete to authenticated
  using (app.is_admin());

drop policy if exists patient_lab_results_select on public.patient_lab_results;
create policy patient_lab_results_select on public.patient_lab_results
  for select to authenticated
  using (app.can_access_patient(patient_id) or app.has_role('lab_tech'));

drop policy if exists patient_lab_results_write on public.patient_lab_results;
create policy patient_lab_results_write on public.patient_lab_results
  for all to authenticated
  using (app.has_role('owner', 'admin', 'doctor', 'nurse', 'lab_tech') and app.can_access_patient(patient_id))
  with check (app.has_role('owner', 'admin', 'doctor', 'nurse', 'lab_tech') and app.can_access_patient(patient_id));

-- Doctor locations: names are harmless clinic-wide (needed for
-- appointment/note location pickers), but only the owning doctor
-- (or an admin) can manage the list.
drop policy if exists doctor_locations_select on public.doctor_locations;
create policy doctor_locations_select on public.doctor_locations
  for select to authenticated
  using (app.is_staff());

drop policy if exists doctor_locations_write on public.doctor_locations;
create policy doctor_locations_write on public.doctor_locations
  for all to authenticated
  using (app.is_admin() or doctor_id = app.staff_id())
  with check (app.is_admin() or doctor_id = app.staff_id());

grant select, insert, update, delete on public.patient_medications   to authenticated;
grant select, insert, update, delete on public.staff_notes           to authenticated;
grant select, insert, delete         on public.staff_note_recipients to authenticated;
grant select, insert, update, delete on public.patient_contact_log   to authenticated;
grant select, insert, update, delete on public.patient_lab_results   to authenticated;
grant select, insert, update, delete on public.doctor_locations      to authenticated;

revoke all on all tables    in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke all on all functions in schema public from anon;

insert into app.schema_migrations (version, name)
values ('0013', 'outpatient_extras')
on conflict (version) do nothing;

commit;


-- ####################  0014_patient_orders.sql  ####################

-- =============================================================
-- 0014_patient_orders.sql
-- Doctor's orders for an outpatient visit: labs, imaging, procedures,
-- medications, and general instructions. Written as free text, captured
-- as a draft, then signed -- signing is what makes an order real.
--
-- Outpatient shape on purpose. SIMA's version of this table carried an
-- inpatient medication-administration schedule (frequency_hours,
-- total_occurrences, a per-dose administrations child table, and
-- pharmacy stock deduction driving a nurse Care Queue). None of that
-- applies in a clinic where the patient walks out with a prescription,
-- so it isn't here: an order is written, signed, and later marked
-- completed or cancelled.
--
-- Safe to re-run.
-- =============================================================

begin;

do $$ begin
  create type public.patient_order_type as enum (
    'lab', 'imaging', 'procedure', 'medication', 'referral', 'other'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.patient_order_status as enum (
    'draft', 'active', 'completed', 'cancelled'
  );
exception when duplicate_object then null; end $$;

create table if not exists public.patient_orders (
  id             uuid primary key default gen_random_uuid(),
  patient_id     uuid not null references public.patients (id)     on delete cascade,
  encounter_id   uuid references public.encounters (id)            on delete set null,
  appointment_id uuid references public.appointments (id)          on delete set null,

  order_type     public.patient_order_type   not null default 'other',
  status         public.patient_order_status not null default 'draft',

  -- What the doctor actually typed. Kept verbatim so an order always
  -- reads back the way it was written, whatever the parser made of it.
  order_text     text not null,
  -- Best-effort structure pulled out of order_text at entry time.
  item_name      text,
  dose           text,
  route          text,
  frequency      text,
  instructions   text,

  ordered_by     uuid references public.staff (id) on delete set null,
  signed_at      timestamptz,
  signed_by      uuid references public.staff (id) on delete set null,
  completed_at   timestamptz,
  cancelled_at   timestamptz,
  cancelled_by   uuid references public.staff (id) on delete set null,

  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),

  -- A signed order must record who signed it and when; a draft must not
  -- look signed. Keeps "is this order real?" answerable from one column.
  constraint patient_orders_signed_chk check (
    (status = 'draft' and signed_at is null and signed_by is null)
    or (status <> 'draft' and signed_at is not null)
  )
);

create index if not exists patient_orders_patient_idx on public.patient_orders (patient_id, created_at desc);
create index if not exists patient_orders_status_idx  on public.patient_orders (status);
create index if not exists patient_orders_doctor_idx  on public.patient_orders (ordered_by, created_at desc);

drop trigger if exists patient_orders_set_updated_at on public.patient_orders;
create trigger patient_orders_set_updated_at
  before update on public.patient_orders
  for each row execute function app.set_updated_at();

-- =============================================================
-- POLICIES
-- =============================================================

alter table public.patient_orders enable row level security;

-- Drafts are the author's private scratch space -- nobody else sees an
-- order until it's signed. Everything signed is visible to anyone with
-- a care relationship to the patient, plus lab techs and nurses who
-- have to act on it.
drop policy if exists patient_orders_select on public.patient_orders;
create policy patient_orders_select on public.patient_orders
  for select to authenticated
  using (
    ordered_by = app.staff_id()
    or (
      status <> 'draft'
      and (app.can_access_patient(patient_id) or app.has_role('nurse', 'lab_tech'))
    )
  );

drop policy if exists patient_orders_insert on public.patient_orders;
create policy patient_orders_insert on public.patient_orders
  for insert to authenticated
  with check (
    app.has_role('owner', 'admin', 'doctor')
    and ordered_by = app.staff_id()
    and app.can_access_patient(patient_id)
  );

-- The author (or an admin) edits and signs their own orders. Nurses and
-- lab techs may update too -- that's how an active order gets marked
-- completed once the test is drawn or the procedure is done.
drop policy if exists patient_orders_update on public.patient_orders;
create policy patient_orders_update on public.patient_orders
  for update to authenticated
  using (
    app.is_admin()
    or ordered_by = app.staff_id()
    or (status <> 'draft' and app.has_role('nurse', 'lab_tech'))
  )
  with check (
    app.is_admin()
    or ordered_by = app.staff_id()
    or (status <> 'draft' and app.has_role('nurse', 'lab_tech'))
  );

-- Only an unsigned draft can be thrown away. A signed order is part of
-- the record and gets cancelled, not deleted.
drop policy if exists patient_orders_delete on public.patient_orders;
create policy patient_orders_delete on public.patient_orders
  for delete to authenticated
  using (status = 'draft' and (app.is_admin() or ordered_by = app.staff_id()));

grant select, insert, update, delete on public.patient_orders to authenticated;

revoke all on all tables    in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke all on all functions in schema public from anon;

insert into app.schema_migrations (version, name)
values ('0014', 'patient_orders')
on conflict (version) do nothing;

commit;
