-- ============================================================================
-- SIMA — extracted DDL (structure only, no data)
--
-- Source: C:\Maleks System\Sima\schema_consolidated.sql
-- Extracted: 2026-07-24
--
-- Scope: patients, appointments, and users/staff (profiles), as requested.
-- Everything else in SIMA's schema (rooms, doctor_locations, doctor_shifts,
-- lab results, visit notes, pharmacy, and the whole hospital ADT block —
-- hospital_floors/wards/ward_rooms/beds/admissions/bed_transfers) is
-- intentionally NOT reproduced here: it's either hospital-specific
-- (excluded per instructions) or out of the four requested entities.
--
-- INVOICES: SIMA has no patient-invoicing/billing table. The only
-- "invoice_number" field in the whole schema is a free-text column on
-- pharmacy_purchases (a vendor purchase-order reference, not a patient
-- invoice — see note at the bottom of this file). There is nothing to
-- extract for that entity. The polyclinic app's own
-- supabase/migrations/0006_billing.sql (services/invoices/invoice_items/
-- payments) is original work, not adapted from SIMA.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- users/staff — SIMA calls this "profiles": one row per Supabase Auth login,
-- role stored as a free-text column constrained by a CHECK, not an enum or a
-- separate roles table. Polyclinic app's equivalent is public.staff
-- (supabase/migrations/0002_staff_and_roles.sql) — same shape, different
-- name, and clinic-scoped rather than global since polyclinic app is one
-- Supabase project per clinic.
-- ---------------------------------------------------------------------------
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text not null default 'secretary',
  phone text,
  created_at timestamptz not null default now(),
  constraint profiles_role_check check (role in ('admin', 'doctor', 'secretary', 'pharmacy', 'nurse'))
);

-- Auto-creates a profile row whenever someone is added to Supabase Auth.
-- (Included because it's load-bearing for how "users/staff" actually gets
-- populated in SIMA — there's no separate staff-creation insert path other
-- than this trigger plus the server-side /api/admin/create-staff endpoint.)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    'secretary'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- patients — full demographic + personal-details record. Primary key is a
-- generated numeric MRN (not a uuid) — the app then re-encodes it for
-- display (see formatMRNDisplay in PatientsDirectory.tsx). Note the
-- case-insensitive uniqueness constraint on identity, used as SIMA's
-- duplicate-patient guard.
-- ---------------------------------------------------------------------------
create table public.patients (
  mrn bigint generated by default as identity primary key,
  first_name text not null,
  surname text not null,
  birth_date date not null,
  gender text,
  phone_number text,
  email text,
  address text,
  history text,
  father_name text,
  mother_name text,
  national_id text,
  nationality text,
  place_of_birth text,
  marital_status text,
  occupation text,
  education_level text,
  emergency_contact_name text,
  emergency_contact_relation text,
  emergency_contact_phone text,
  insurance_provider text,
  insurance_number text,
  blood_type text,
  created_at timestamptz not null default now()
);

-- No two patients may share first + father + surname + birth date (case-insensitive).
create unique index if not exists patients_identity_unique
  on public.patients (
    lower(first_name),
    coalesce(lower(father_name), ''),
    lower(surname),
    birth_date
  );

-- ---------------------------------------------------------------------------
-- appointments — references rooms and doctor_locations, which are NOT
-- extracted here (out of the requested four entities). If you rebuild this
-- table standalone, those two foreign keys need either a stub table or to be
-- dropped/replaced with polyclinic app's own scheduling tables
-- (supabase/migrations/0004_scheduling.sql already has rooms +
-- doctor_schedules + appointments of its own).
-- ---------------------------------------------------------------------------
create table public.appointments (
  id bigint generated by default as identity primary key,
  patient_mrn bigint not null references public.patients(mrn) on delete cascade,
  doctor_id uuid references public.profiles(id) on delete set null,
  room_id bigint references public.rooms(id) on delete set null,
  schedule_time timestamptz not null,
  duration_hours integer not null default 1,
  location_id bigint references public.doctor_locations(id) on delete set null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- invoices — does not exist in SIMA. For reference, the only adjacent
-- column anywhere in the schema is this one, on a vendor purchase table
-- (pharmacy buying stock from a supplier — not a patient bill):
--
--   create table public.pharmacy_purchases (
--     ...
--     invoice_number text,
--     ...
--   );
--
-- There is no patient-facing invoice, invoice_items, payment, or billing
-- table in SIMA at all. Nothing further to extract.
-- ---------------------------------------------------------------------------
