-- =============================================================
-- 0011_lab_parameters.sql
-- Reference catalog of lab test parameters (category/units/reference
-- range), mirroring SIMA's public.lab_parameters. Used as an
-- autocomplete/validation catalog when recording a result, not
-- patient data itself.
--
-- Note: SIMA's UI also reads a public.patient_lab_results table (results
-- joined to this catalog via parameter_id) that this app doesn't have
-- yet either -- this migration only adds the reference catalog, not
-- that results table. See docs/sima-interface.md.
--
-- Safe to re-run.
-- =============================================================

begin;

create table if not exists public.lab_parameters (
  id              bigint generated by default as identity primary key,
  category        text,
  test_name       text not null,
  units           text,
  reference_range text,
  created_at      timestamptz not null default now(),
  constraint lab_parameters_test_name_key unique (test_name)
);

alter table public.lab_parameters enable row level security;

drop policy if exists lab_parameters_select on public.lab_parameters;
create policy lab_parameters_select on public.lab_parameters
  for select to authenticated
  using (app.is_staff());

drop policy if exists lab_parameters_write on public.lab_parameters;
create policy lab_parameters_write on public.lab_parameters
  for all to authenticated
  using (app.has_role('owner', 'admin', 'doctor', 'nurse', 'lab_tech'))
  with check (app.has_role('owner', 'admin', 'doctor', 'nurse', 'lab_tech'));

grant select, insert, update on public.lab_parameters to authenticated;

insert into public.lab_parameters (category, test_name, units, reference_range) values
  ('KIDNEY',    'eGFR (CKD-EPI)',          'mL/min/1.73m2', '>= 90'),
  ('KIDNEY',    'Serum Creatinine',        'mg/dL',         '0.70 - 1.30'),
  ('KIDNEY',    'BUN (Blood Urea Nitrogen)', 'mg/dL',       '7 - 20'),
  ('LIPIDS',    'Total Cholesterol',       'mg/dL',         '< 200'),
  ('LIPIDS',    'LDL Cholesterol (Calc)',  'mg/dL',         '< 100'),
  ('LIPIDS',    'HDL Cholesterol',         'mg/dL',         '> 35'),
  ('LIPIDS',    'Triglycerides',           'mg/dL',         '< 150'),
  ('GLYCAEMIC', 'HbA1c',                   '%',             '4.0 - 5.6'),
  ('GLYCAEMIC', 'Fasting Blood Glucose',   'mg/dL',         '70 - 99'),
  ('HEMATOLOGY','RBC Count',               'M/ul',          '4.5 - 6.5'),
  ('HEMATOLOGY','Hemoglobin',              'g/dL',          '13 - 18'),
  ('HEMATOLOGY','Hematocrit',              '%',             '40 - 54'),
  ('HEMATOLOGY','MCV',                     'fl',            '80 - 94'),
  ('HEMATOLOGY','WBC Count',               'K/ul',          '4.0 - 11.0'),
  ('HEMATOLOGY','Platelet Count',          'K/ul',          '150 - 450'),
  ('LIVER',     'ALT (SGPT)',              'U/L',           '7 - 56'),
  ('LIVER',     'AST (SGOT)',              'U/L',           '10 - 40'),
  ('LIVER',     'ALP (Alkaline Phosphatase)', 'U/L',        '44 - 147'),
  ('ELECTROLYTES', 'Sodium',               'mmol/L',        '135 - 145'),
  ('ELECTROLYTES', 'Potassium',            'mmol/L',        '3.5 - 5.1'),
  ('THYROID',   'TSH',                     'uIU/mL',        '0.4 - 4.0')
on conflict (test_name) do nothing;

revoke all on all tables    in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke all on all functions in schema public from anon;

insert into app.schema_migrations (version, name)
values ('0011', 'lab_parameters')
on conflict (version) do nothing;

commit;
